#!/usr/bin/env python3
"""Regenerate the synthetic test SAM files from reference.fasta.

Reads are exact copies of HXB2 (K03455) amplicon regions with a few known
drug-resistance mutations spiked in. The trailing `_<n>` in each read name is
the read multiplicity understood by codonyat, which keeps the files tiny.

  Amp_1  RT codons   1-80   (HXB2 2550-2789)
  Amp_2  RT codons 150-200  (HXB2 2997-3149)

sample1: M41L (~30%), K65R (~10%), M184V (50%), strand-balanced
sample2: wild type plus a forward-strand-only K65R artefact and a read
         carrying a 3-nt deletion of codon 69

Usage: python3 make_testdata.py   (run inside assets/testdata)
"""
from pathlib import Path

REF_NAME = "K03455|HIVHXB2CG"
AMPLICONS = {"Amp_1": (2550, 2789), "Amp_2": (2997, 3149)}

seq = "".join(l.strip() for l in open("reference.fasta") if not l.startswith(">"))


def region(start, end):
    return seq[start - 1 : end]


def mutate(read, read_start, pos, new_base):
    i = pos - read_start
    return read[:i] + new_base + read[i + 1 :]


def record(name, flag, start, cigar, read):
    return "\t".join([name, str(flag), REF_NAME, str(start), "60", cigar, "*", "0", "0", read, "I" * len(read)])


def write_sam(path, records):
    header = [
        "@HD\tVN:1.6\tSO:unsorted",
        f"@SQ\tSN:{REF_NAME}\tLN:{len(seq)}",
        "@CO\tsynthetic test data generated by make_testdata.py",
    ]
    Path(path).write_text("\n".join(header + records) + "\n")


def reads_for(amp, variants):
    """variants: list of (label, {pos: base}, fw_count, rv_count)"""
    start, end = AMPLICONS[amp]
    wt = region(start, end)
    out = []
    for label, muts, fw, rv in variants:
        read = wt
        for pos, base in muts.items():
            read = mutate(read, start, pos, base)
        cigar = f"{len(read)}M"
        if fw:
            out.append(record(f"{amp}_{label}_fw_{fw}", 0, start, cigar, read))
        if rv:
            out.append(record(f"{amp}_{label}_rv_{rv}", 16, start, cigar, read))
    return out


# Codon start positions in HXB2 numbering: RT codon c starts at 2550 + 3*(c-1)
M41L = {2670: "C"}  # ATG -> CTG
K65R = {2743: "G"}  # AAA -> AGA
M184V = {3099: "G"}  # ATG -> GTG

sample1 = reads_for("Amp_1", [("wt", {}, 18, 17), ("M41L", M41L, 6, 7), ("K65R", K65R, 3, 2)])
sample1 += reads_for("Amp_2", [("wt", {}, 10, 10), ("M184V", M184V, 10, 10)])

sample2 = reads_for("Amp_1", [("wt", {}, 20, 20), ("K65Rfw", K65R, 5, 0)])
# one read pair-equivalent with a 3-nt deletion of RT codon 69 (HXB2 2754-2756)
s, e = AMPLICONS["Amp_1"]
d0 = 2754 - s
deleted = region(s, e)[:d0] + region(s, e)[d0 + 3 :]
sample2.append(record("Amp_1_T69del_fw_2", 0, s, f"{d0}M3D{len(deleted) - d0}M", deleted))
sample2.append(record("Amp_1_T69del_rv_2", 16, s, f"{d0}M3D{len(deleted) - d0}M", deleted))
sample2 += reads_for("Amp_2", [("wt", {}, 15, 15)])

write_sam("sample1.sam", sample1)
write_sam("sample2.sam", sample2)
